export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const FAILED_COUNTRIES = 'FAILED_COUNTRIES';

export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const FAILED_PROJECTS = 'FAILED_PROJECTS';
export const SELECT_PROJECT = 'SELECT_PROJECT';